name: Run Tests with Headless Browsers

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Install Browsers
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser firefox

    - name: Run Tests with pytest
      run: |
        pipenv run pytest --html=report.html --self-contained-html
      continue-on-error: false

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.html